# Generated by Django 2.2.4 on 2019-08-23 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='subject')),
                ('message', models.CharField(blank=True, max_length=300, null=True, verbose_name='message')),
                ('created', models.DateField(auto_now_add=True, db_index=True, verbose_name='create date')),
                ('unread', models.BooleanField(db_index=True, default=True, verbose_name='unread')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rcv', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'message',
            },
        ),
    ]
